#!/usr/bin/env bash
# Generate a coverage table from per-service JaCoCo reports and splice it into README.md
# between the `<!-- coverage:start -->` / `<!-- coverage:end -->` markers.
#
# Expects each service's report at:
#   <service>/target/site/jacoco/jacoco.xml
#
# In CI: runs after every test matrix job's jacoco artifact has been downloaded into
# place. Locally: run `./run-all-tests.sh` first, then this script.
#
# Exits 0 even if no readme change is needed — caller commits only if `git diff` is non-empty.

set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
README="$REPO_ROOT/README.md"
SERVICES=(config-server auth-service catalog-service playlist-service streaming-service notification-service)

extract_counter() {
  local xml="$1" type="$2"
  grep -oE "<counter type=\"$type\" missed=\"[0-9]+\" covered=\"[0-9]+\"/>" "$xml" | tail -1
}

total_l_cov=0; total_l_total=0
total_b_cov=0; total_b_total=0
table_rows=""

for svc in "${SERVICES[@]}"; do
  xml="$REPO_ROOT/$svc/target/site/jacoco/jacoco.xml"
  if [ ! -f "$xml" ]; then
    table_rows+="| \`$svc\` | _no report_ | _no report_ |"$'\n'
    continue
  fi

  line=$(extract_counter "$xml" LINE)
  branch=$(extract_counter "$xml" BRANCH)

  l_miss=$(echo "$line" | grep -oE 'missed="[0-9]+"' | tr -dc '0-9'); : "${l_miss:=0}"
  l_cov=$(echo "$line" | grep -oE 'covered="[0-9]+"' | tr -dc '0-9'); : "${l_cov:=0}"
  b_miss=$(echo "$branch" | grep -oE 'missed="[0-9]+"' | tr -dc '0-9'); : "${b_miss:=0}"
  b_cov=$(echo "$branch" | grep -oE 'covered="[0-9]+"' | tr -dc '0-9'); : "${b_cov:=0}"

  l_total=$((l_miss + l_cov))
  b_total=$((b_miss + b_cov))
  l_pct=$([ "$l_total" -gt 0 ] && echo $((100 * l_cov / l_total)) || echo "—")
  b_pct=$([ "$b_total" -gt 0 ] && echo $((100 * b_cov / b_total)) || echo "—")

  l_cell=$([ "$l_pct" = "—" ] && echo "—" || echo "**${l_pct}%** ($l_cov/$l_total)")
  b_cell=$([ "$b_pct" = "—" ] && echo "—" || echo "**${b_pct}%** ($b_cov/$b_total)")
  table_rows+="| \`$svc\` | $l_cell | $b_cell |"$'\n'

  total_l_cov=$((total_l_cov + l_cov))
  total_l_total=$((total_l_total + l_total))
  total_b_cov=$((total_b_cov + b_cov))
  total_b_total=$((total_b_total + b_total))
done

total_l_pct=$([ "$total_l_total" -gt 0 ] && echo $((100 * total_l_cov / total_l_total)) || echo "—")
total_b_pct=$([ "$total_b_total" -gt 0 ] && echo $((100 * total_b_cov / total_b_total)) || echo "—")

table=$(cat <<EOF
<!-- coverage:start -->
_Last regenerated by CI on \$(date -u +%Y-%m-%d). See [\`scripts/coverage-summary.sh\`](scripts/coverage-summary.sh)._

| Service | Line coverage | Branch coverage |
|---|---|---|
${table_rows}| **Aggregate** | **${total_l_pct}%** (${total_l_cov}/${total_l_total}) | **${total_b_pct}%** (${total_b_cov}/${total_b_total}) |
<!-- coverage:end -->
EOF
)

# Replace the marker block in README. Use awk for portable in-place edit.
tmp="$(mktemp)"
awk -v block="$table" '
  /<!-- coverage:start -->/ { print block; in_block=1; next }
  /<!-- coverage:end -->/   { in_block=0; next }
  !in_block                  { print }
' "$README" > "$tmp"
mv "$tmp" "$README"

# Substitute the date placeholder (awk above keeps the literal $(date) string)
date_str=$(date -u +%Y-%m-%d)
sed -i.bak "s/\\\$(date -u +%Y-%m-%d)/$date_str/" "$README"
rm -f "$README.bak"

echo "Coverage table updated in README.md"
echo "Aggregate: ${total_l_pct}% lines / ${total_b_pct}% branches"
